# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 23:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='objects_to_watch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='sms_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='stream_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='youtube_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
