# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20170412_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='stream_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
